### ISSUE TITLE
Report disconnection

### ISSUE THREAD

**Issue by mrkam2** [forcedotcom/EMP-Connector#13]
As it was mention in another issue https://github.com/forcedotcom/EMP-Connector/issues/4, the subscription becomes dead after a period of time without the client being notified. Is it possible to report disconnection so that the client can reconnect?

**Comment by sfdc-hhildebrand** [comment]
Yes.  I am reworking this on the other branch, which will hopefully include some new things like this.  Currently, it's reconnecting always, but I will rework that into a better handler pattern with auth failures and others

**Comment by mrkam2** [comment]
Cool, do you have a timeline for it?

**Comment by mrkam2** [comment]
I looked into that branch and it looked abandoned to me :-) Especially because there was something fixed on the server side.

**Comment by sfdc-hhildebrand** [comment]
Yes, that fix solved the immediate problem that instigated the branch.  I've branched that yet again for internal work I'm doing.   But I have some good ideas I would like to integrate back in and the handling of the connection failure is basically the work needed to do what this issue is asking.  Simply replace the retry with a callback registered with the connector.

I can't promise when I can get to this as we're approaching release freeze and I'm stretched pretty thin on the backend server side of things.

**Comment by deepakkapoor23** [comment]
Is there a fix/workaround/extension available for this in the master branch? It doesn't seem to be reconnecting automatically as claimed by the author.

**Comment by johnsonlu** [comment]
Is there any update on this issue?

**Comment by pbn-sfdc** [comment]
This is fixed, after re-handshake the EmpConnector will automatically subscribe to topics.

**Comment by pbn-sfdc** [comment]
Closing this.
